name: Lint

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-lint:
    name: Lint Markdown and HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: github/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: /github/workspace/.markdownlint.yaml
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_CSS: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_CSHARP: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_SQL: true
          VALIDATE_XML: true
          VALIDATE_POWERSHELL: true
          VALIDATE_BASH: true
          VALIDATE_PYTHON: true
